image: node:10.13.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # Restore last modified time
  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"

pages:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
  
  # install cli
  - yarn global add hexo-cli
  
  # update dependencies
  - yarn install

  # clean
  - hexo clean

  # generate another theme
  - hexo generate --config themes/artchen-typescript.yml
  - mv public temp_public

  # clean
  - hexo clean
  # generate next theme
  - hexo generate

  # others
  - cp robots.txt public
  - mv temp_public public/simple

  environment:
    name: page

  artifacts:
    paths:
      - public
    expire_in: 3 mos

  only:
    - tags
    - master

github:
  stage: deploy
  script:
    - git config --global user.name "jiangtj"
    - git config --global user.email "jiang.taojie@foxmail.com"
    - cd ./public
    - git init
    - git add .
    - git commit -m "gitlab-auto-deploy"
    - git push --force --quiet --set-upstream https://$GITHUB_ACCESS_TOKEN@github.com/jiangtj/jiangtj.github.io.git master
  only:
    - tags
