variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image: node:10.13.0
  cache:
    paths:
    - node_modules/

  script:

  - ls themes/next-sub
  
  # install cli
  - yarn global add hexo-cli
  
  # update dependencies
  - yarn install

  # clean
  - hexo clean

  # generate another theme
  - hexo generate --config themes/artchen-typescript.yml
  - mv public temp_public

  # generate next theme
  - hexo generate

  # others
  - cp robots.txt public
  - mv temp_public public/simple

  environment:
    name: page

  artifacts:
    paths:
    - public
    expire_in: 3 mos

  only:
  - master
